%%{init: {"theme": "neutral", "fontFamily": "arial", "curve": "linear"} }%%

flowchart LR
    classDef emphasis fill:#03A062;

    script["array script"] -->|"video 1"| GPU1["GPU 1"] --> model1["predictions 1"]
    script -->|"video 2"| GPU2GPU1["GPU 2"] --> model2["predictions 2"]
    script -->|"video n"| GPU3GPU1["GPU n"] --> model3["predictions n"]

    class script emphasis